ChatGPT basic app and script
wolfSSL/wolfcrypt-jni pull request #88
Opened 2024-12-23 18:49 UTC by jackctj117

Started outline for wolfJSSE Bouncy Castle benchmark.

2024-12-23 19:30 UTC, cconlon requested changes
See feedback comments. Also please rename commit to mention "wolfJCE" instead of "wolfJSSE". This is only a crypto-level benchmark, not an SSL/TLS benchmark (JSSE level).

2024-12-23 19:30 UTC, cconlon commented on examples/provider/CryptoBenchmark.java
> +            // Generate a random key and IV
Please switch C++ style comments (`//`) to match our coding standards (`/* */`)

2024-12-23 19:30 UTC, cconlon commented on examples/provider/CryptoBenchmark.java
> +            warmup(testData, key, iv);
I suggest having one method per Java Security API class.  For example, this is benchmarking the `Cipher` class, so we could have one method called `benchmarkCipher()` which is called from `main()`. Array allocations, and behavior contained in warmup and benchmarkOperation() here could move into that method.

2024-12-23 19:30 UTC, cconlon commented on examples/provider/CryptoBenchmark.java
> +            byte[] ivBytes = new byte[16];
`16` should be moved into a variable (ex: `AES_BLOCK_SIZE`).

2024-12-23 19:30 UTC, cconlon commented on examples/provider/CryptoBenchmark.java
> +            long encryptTime = benchmarkOperation("encrypt", testData, key, iv);
Let's keep with our coding standard and define all variables at the top of a method.

2024-12-23 20:05 UTC, jackctj117 commented
Newest push should fix previous concerns

2024-12-23 20:46 UTC, cconlon commented on examples/provider/CryptoBenchmark.java
> +            long encryptTime = benchmarkOperation("encrypt", testData, key, iv);
This is still outstanding, I still see variables declared in the middle of a method instead of at the top of it.

2024-12-23 20:48 UTC, cconlon requested changes

2024-12-23 20:48 UTC, cconlon commented on examples/provider/CryptoBenchmark.java
> +import com.wolfssl.provider.jsse.WolfSSLProvider;
This is a JCE example, not JSSE. This should be importing the wolfJCE / WolfCryptProvider:

```
import com.wolfssl.provider.jce.WolfCryptProvider;
```

2024-12-23 23:21 UTC, cconlon requested changes

2024-12-23 23:21 UTC, cconlon commented on examples/provider/CryptoBenchmark.java
> +        System.out.println("  Version: " + provider.getVersionStr());
There is no `Provider.getVersionStr()` method (https://docs.oracle.com/javase/8/docs/api/java/security/Provider.html).

2024-12-24 17:31 UTC, jackctj117 commented on examples/provider/CryptoBenchmark.java
> +        System.out.println("  Version: " + provider.getVersionStr());
changed to .getVersion()

2024-12-24 21:17 UTC, cconlon requested changes
A few more comments.  Also please squash all commits into a single one.

2024-12-24 21:17 UTC, cconlon commented on examples/provider/CryptoBenchmark.sh
> +# Before running this script macOS,
I suggest making this script much simpler. See how `examples/provider/ProviderTest.sh` looks, we should be able to do nearly the same until we start adding more providers in.

2024-12-24 21:17 UTC, cconlon commented on examples/provider/CryptoBenchmark.java
> +        System.out.println("\nResults (average time per operation):");
Let's make an incremental improvement on the benchmark output, so that it looks very similar to how the native wolfCrypt benchmark app (./wolfcrypt/benchmark/benchmark) looks. This will be more consistent and more concise.

2024-12-24 22:03 UTC, cconlon commented on examples/provider/CryptoBenchmark.java
> +        System.out.println("\nResults (average time per operation):");
As discussed offline, saving for a future PR.

2024-12-24 22:17 UTC, cconlon approved these changes

2024-12-24 22:17 UTC, merged